version: 2.1
orbs:
  aws-cli: circleci/aws-cli@5.1
  aws-ecr: circleci/aws-ecr@9.7.0

workflows:
  build-and-push-image-with-container-registry-login:
    jobs:
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/assume-role-with-web-identity:
                role-arn: '${CIRCLECI_OIDC_ROLE_ARN}'
          container_registry_login: true
          dockerfile: Dockerfile
          path: .
          region: '${AWS_REGION}'
          repo: 'nginx'
          tag: '${CIRCLE_SHA1}'
          context: AWS

      ### ECSへデプロイするジョブ
      #- aws-ecs/deploy-service-update:
      #    requires:
      #      - aws-ecr/build-and-push-image
      #    family: 'circleci-book-task'
      #    service-name: 'circleci-book-service'
      #    cluster-name: 'circleci-book-cluster'
      #    container-image-name-updates: 'container=circleci-book-container,image-and-tag=${AWS_ECR_ACCOUNT_URL}/nginx:${CIRCLE_SHA1}'

### E2Eテストの例
#version: 2
#jobs:
#  run_e2e_test:
#    docker:
#      - image: circleci/ruby:2.6.5
#    working_directory: ~/project
#    steps:
#      - checkout
#      - run: bundle install
#      - run: bundle exec ruby e2e.rb "https://google.com"
#
#workflows:
#  version: 2
#  monitoring:
#    triggers:
#      - schedule:
#          cron: "* * * * *"
#          filters:
#            branches:
#              only:
#                - master
#    jobs:
#      - run_e2e_test
